spring.application.name=novosiga

#Definir o banco de dados para a conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/db_novosiga
spring.datasource.username=postgres
spring.datasource.password=221145

#Configurações do JPA/Hibernate

#Atualiza o banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

#Limpar o cache para a execução do Thymeleaf 
spring.thymeleaf.cache=false

#Exibir no terminal o SQL sendo executado
spring.jpa.show-sql=true

